### ISSUE TITLE
502 error on some pages on nginx/uwsgi server

### ISSUE THREAD

**Issue by jabrouwer82** [plberg/cs373-idb#36]
celebrities/, crimes/ and / work, but celebrities/1/ doesn't and neither does charges/

**Comment by jabrouwer82** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./views.py", line 36, in charges
    return render_template('charges.html', charges=charge_list, date_formatter=date_formatter)
  File "/usr/local/lib/python3.4/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.4/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/home/jacob/cs373-idb/templates/charges.html", line 1, in <module>
    {% extends "base.html" %}
  File "/home/jacob/cs373-idb/templates/base.html", line 43, in <module>
    {% block content %}{% endblock %}
  File "/home/jacob/cs373-idb/templates/charges.html", line 13, in <module>
    <dd> {{ charge.crime.name }} - {{ charge.location }} ({{ date_formatter(charge.date) }}) </dd>
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 397, in getattr
    return getattr(obj, attribute)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/attributes.py", line 239, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/attributes.py", line 591, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/strategies.py", line 535, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/strategies.py", line 580, in _emit_lazyload
    return loading.load_on_ident(q, ident_key)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/loading.py", line 235, in load_on_ident
    return q.one()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2398, in one
    ret = list(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2441, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2456, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) column crime.description does not exist
LINE 1: ...T crime.id AS crime_id, crime.name AS crime_name, crime.desc...
                                                             ^
 'SELECT crime.id AS crime_id, crime.name AS crime_name, crime.description AS crime_description, crime.wiki_url AS crime_wiki_url \nFROM crime \nWHERE crime.id = %(param_1)s' {'param_1': 2}

**Comment by jabrouwer82** [comment]
I think I might have borken this last night when I added a description field to crimes.

**Comment by jabrouwer82** [comment]
I believe this is resolved. Updating the database seems to have fixed is.
