### ISSUE TITLE
502 error from /celebrities /crimes, etc

### ISSUE THREAD

**Issue by jabrouwer82** [plberg/cs373-idb#75]
This is on the deployed application

**Comment by jabrouwer82** [comment]
Now occurs on /celebrity but not /charge on my local build

**Comment by jabrouwer82** [comment]
It's spreading, now every endpoint I hit gives a 502.

**Comment by jabrouwer82** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args) 
 File "./views.py", line 64, in getCrime
    crime_info = Crime.query.filter(Crime.name == crime).first()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2370, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2231, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2441, in **iter**
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2456, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) relation "crime" does not exist
LINE 2: FROM crime
             ^
 'SELECT crime.id AS crime_id, crime.name AS crime_name, crime.description AS crime_description, crime.wiki_url AS crime_wiki_url \nFROM crime \nWHERE crime.name = %(name_1)s \n LIMIT %(param_1)s' {'name_1': 'Possession of Marijuana', 'param_1': 1}

**Comment by jabrouwer82** [comment]
Running init_db solved the issue.
